- applespi.c
Regarding power consumption, you might be looking in the wrong place if you're searching for the interrupt in `/proc/interrupts`. The DSDT shows that GPE 0x1C sends a device notification, so you need to look at `/sys/firmware/acpi/interrupts/gpe1C` and see under which conditions it increases. Is the GPE only used for wake from system sleep or is it used for power management? If the latter, perhaps you need to stop polling after a period of inactivity and power down the device with SIEN(0), then wait for the device to send a notification and power it up with SIEN(1). You can call SIEN using `acpi_execute_simple_method()`, see l1k/linux@65f56e6c84462335e19b780e5d3140b769d97963 for an example. To make use of the GPE, call `acpi_install_notify_handler()` and `acpi_enable_gpe()`, see …
> applespi: Document ACPI methods

- README.md
- applespi.c
This was tested on a MBP Late 2016, i.e. with touchbar, so haven't tested the F1-F12 keys. This also means the driver works on these new MBP's (modulo a small hiccup) - many thanks!
> Implement function key

- applespi.c
Apologies for sending this in one pull request, but I'm too lazy to try and tear things apart. The two big features where are the fixes to make trackpad initialization reliable, and to toggle the caps-locks led. Besides that there are some cleanups/re-factorings that I hope are acceptable.
This should fix issues #6 and #3, and is also related to #9.
> Init fixes and caps lock led support

- Makefile
This is needed if you want to build against a different than the running kernel, e.g. using dkms.
> fix Makefile to use correct kernel version

- applespi.c
> applespi: Introduce delay between cs and receive on reads.

- applespi.c
Unlike the hid-apple driver, we don't have any idea whether the current
keyboard is using the iso-layout or not. This means that the iso_layout
has subtly different semantics here than on hid-apple (from which this
was copied): rather than just allowing for disabling of the iso-layout
on iso keyboards, the flag here determines which layout is used on all
keyboards. Therefore the flag's default should reflect the most common
keyboard type, which is not iso.
> applespi: Change the default for iso-layout to disabled.

- README.md
- applespi.c
This creates the spi device based on information taken from the _DSM method. While a more complete fix should probably be done in the core, this at least avoids the need for DSDT modifications right now - most of this should be removed again when the core has the desired support. Partly for this reason all the added code uses the `appleacpi_` prefix instead of the `applespi_` prefix used everywhere else in this module, thereby making it clear that it A) is related to acpi not spi per se, and B) is a piece of functionality that can be removed together. But feedback/comments welcome.
This resolves #21 for now.
> applespi: Remove the need to modify the DSDT.

- applespi.c
I assume you already started adding this functionality to the driver, but I got impatient and too excited about having the backlight working after you posted your traces in Dunedan/mbp-2016-linux#16 that I went ahead and created this. Feel free to ignore, trash, plunder, or otherwise do what you like with this.
> applespi: Add keyboard-backlight support.

- applespi.c
Since the change of the default for the iso_layout parameter the
description pointed to the wrong value as default. This trivial commit
fixes that.
> Fix description of iso_layout parameter

- applespi.c
This adds scan codes for the following keys:
- Ro (_)
- Yen (|)
- Kana (mapped to KEY_KATAKANAHIRAGANA)
- Eisu (mapped to KEY_MUHENKAN)
Fixes #34
Signed-off-by: Samir Ibradzic
> applespi: Support special Japanese layout keys

- README.md
- dkms.conf
Tested on Ubuntu 17.04
Signed-off-by: Samir Ibradzic
> applespi: add simple DKMS support

- applespi.c
4.13 introduced a new guid_t type and changed various functions to take
that instead of a u8*; as part of that acpi_str_to_uuid() was removed
in favor of guid_parse().
This fixes #37 .
> applespi: Add support for new guid type on Linux 4.13+.

- applespi.c
This fixes one of the issues folks have seen on their 2015 MB's (see #9).
> applespi: Make master-spi-device detection more robust.

- applespi.c
This wasn't actually causing any issues AFAICT, since we currently don't look at the response, but nevertheless I figure it doesn't hurt.
> applespi: Fix reading of touchpad init response.

- applespi.c
The 3 changes here are actually independent, but are all related to touchpad dimensions, so I thought it might be easier if I sent them as one pull request.
The logging of touchpad dimesions is a bit more complicated using dynamic-debug instead of simple #ifdef's, but I think the advantage of being able to give folks a simple echo command to run to turn it on instead of asking them recompile outweighs the uglyness - this should be especially true once the module is mainlined and folks get it as part of their distro's kernel.
I'm still not happy about the MB touchpad dimesions. As I mention in the commit message, the fact that the old values and those reported for the MB10,1 have noticeably different aspect ratios doesn't sit well (see also [my …
> Touchpad dimensions updates

- README.md
- applespi.c
I'm submitting this mainly for discussion rather than for actual merging. The biggest problem I see with this as it stands is that it's hard to enable debugging of just some packets, and enabling all results in a _huge_ amount of logging in the kernel log, swamping pretty much everything else (mostly due to the touchpad events). E.g. while it's possible to enable logging of just the touchpad init messages, that's only because they are currently only ones using the `applespi_sync_*` functions, i.e. if something else starts using them in the future then that new stuff would get logged to when enabling logging for these functions. And enabling logging of received events does so for both keyboard and touchpad events. Also, as I've discovered recently, it doesn't seem possible to enable …
> applespi: Convert #ifdef'd debug logs to normal debug logs.

- applespi.c
This fixes the issues on the MBP14,1 reported by @peterychuang on #6.
> Touchpad init fixes 2

- README.md
- applespi.c
This contains the work to exclude the DSDT hacks on kernels 4.14+, as promised in https://github.com/cb22/macbook12-spi-driver/pull/29#issuecomment-327672918 - tested on 4.14-rc1. Also included are some README updates and a small #ifdef fix.
> Updates for 4.14

- applespi.c
Just some basic cleanups. No functional change.
> Formatting cleanup

- README.md
Using spi_pxa2xx_pci removes the need for irqpoll and fixes initramfs https://github.com/cb22/macbook12-spi-driver/issues/50
> Updated required module for MacBook8,1 (2015)

- applespi.c
Sorry for putting several things in one pull request, but there were conflicts when I tried to separate them out.
The big one here is 042729a, the long promised clarification of various fields in, and overall structure of the messages. There are still many unknowns, but I think at least the high level message/packet structures are clear now. The commits following that then capitalize on these structures, and in particular the last commit finally fixes the errors when more than 6 fingers are pressed (tested up to all 11 fingers...).
> Fixes and message structure detailing
